name: Build BeautifulDocs

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches: 
      - main
      - develop

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      NugetApiKey: ${{ secrets.NugetApiKey }}
      ChocoApiKey: ${{ secrets.ChocoApiKey }}

    steps:
      - uses: actions/checkout@v2
        
      - name: GitVersion
        id: gitversion
        uses: PoshCode/Actions/gitversion@v1

      - name: Install-RequiredModules
        uses: PoshCode/Actions/install-requiredmodules@v1

      - name: Build Module
        run: .\build.ps1 -Build -SemVer "${{ steps.gitversion.outputs.LegacySemVerPadded }}"
        shell: pwsh

      - name: Upload Built Module
        uses: actions/upload-artifact@v2
        with:
          name: NexuShell.${{ steps.gitversion.outputs.LegacySemVerPadded }}
          path: .\Output
          
      - name: Write MD Docs with PlatyPS
        run: .\build.ps1 -WriteMdDocs -SemVer "${{ steps.gitversion.outputs.LegacySemVerPadded }}"
        shell: pwsh

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: .\mkdocs_template\mkdocs.yml
          EXTRA_PACKAGES: build-base
          # GITHUB_DOMAIN: github.myenterprise.com
